#!/usr/bin/env php
<?php

$dir = opendir('lib/Zap');

while ($file = readdir($dir)) {
    if (0 === strpos($file, '.') || is_dir('lib/Zap/' . $file)) {
        continue;
    }

    $contents = file_get_contents('lib/Zap/' . $file);

    $contents = preg_replace(
        array(
            '/@copyright (\d{4}-\d{4}) silverorange/',
            '/@copyright (\d{4}) silverorange/'
        ),
        '@copyright $1 silverorange, 2011 Delta Systems',
        $contents
    );

    file_put_contents(
        'lib/Zap/' . $file,
        $contents
    );
}

closedir($dir);
